---
title: Обработка событий DataAdapter
description: Описание событий DataAdapter и способов их использования.
ms.date: 11/30/2020
dev_langs:
- csharp
ms.assetid: 11515b25-ee49-4b1d-9294-a142147c1ec5
ms.prod: sql
ms.prod_service: connectivity
ms.technology: connectivity
ms.topic: conceptual
author: David-Engel
ms.author: v-daenge
ms.reviewer: v-chmalh
ms.openlocfilehash: 003a8e77ad80f83c210ffb565ce4fac5c93c2166
ms.sourcegitcommit: c127c0752e84cccd38a7e23ac74c0362a40f952e
ms.translationtype: HT
ms.contentlocale: ru-RU
ms.lasthandoff: 12/07/2020
ms.locfileid: "96772284"
---
# <a name="handle-dataadapter-events"></a>Обработка событий DataAdapter

[!INCLUDE[appliesto-netfx-netcore-netst-md](../../includes/appliesto-netfx-netcore-netst-md.md)]

[!INCLUDE[Driver_ADONET_Download](../../includes/driver_adonet_download.md)]

Поставщик данных Microsoft SqlClient для SQL Server <xref:Microsoft.Data.SqlClient.SqlDataAdapter> предоставляет три события, которые можно использовать для реагирования на изменения, вносимые в данные в источнике данных. В следующей таблице показаны события `DataAdapter`.

|Событие|Описание|  
|-----------|-----------------|  
|`RowUpdating`|Операция UPDATE, INSERT или DELETE над строкой (путем вызова одного из методов `Update`) готова к работе.|  
|`RowUpdated`|Операция UPDATE, INSERT или DELETE над строкой (путем вызова одного из методов `Update`) завершена.|  
|`FillError`|Во время операции `Fill` произошла ошибка.|  

## <a name="rowupdating-and-rowupdated-events"></a>События RowUpdating и RowUpdated

Событие `RowUpdating` вызывается перед тем, как любое обновление строки в <xref:System.Data.DataSet> будет обработано в источнике данных. Событие `RowUpdated` вызывается после того, как любое обновление строки из `DataSet` было обработано в источнике данных. Поэтому событие `RowUpdating` позволяет изменить операцию обновления до ее выполнения - выполнить дополнительную обработку при обновлении, сохранить ссылку на обновленную строку, отменить текущее обновление, запланировать его для пакетной обработки впоследствии и т. д. Событие `RowUpdated` может оказаться полезным для обработки ошибок и исключений, возникших в ходе обновления. Можно добавить **сведения об ошибке** в `DataSet`, а также **логику повторных попыток** и т. д.

К аргументам <xref:System.Data.Common.RowUpdatingEventArgs> и <xref:System.Data.Common.RowUpdatedEventArgs>, передаваемым событиям `RowUpdating` и `RowUpdated`, относятся свойство `Command` со ссылкой на объект `Command`, применяемый для выполнения обновлений, свойство `Row` со ссылкой на объект `DataRow`, содержащий обновленные сведения, свойство `StatementType`, указывающее тип выполняемого обновления, свойство `TableMapping` (если применимо) и свойство `Status` операции.

С помощью свойства `Status` можно определить, возникла ли в ходе операции ошибка, и при необходимости управлять действиями с текущими и результирующими строками. При выполнении события свойство `Status` совпадает с `Continue` или `ErrorsOccurred`. В следующей таблице показаны значения, которые можно назначить свойству `Status` для управления последующими действиями в ходе обновления.

|Состояние|Описание|  
|------------|-----------------|  
|`Continue`|Продолжить операцию обновления.|  
|`ErrorsOccurred`|Прервать операцию обновления и вызвать исключение.|  
|`SkipCurrentRow`|Пропустить текущую строку и продолжить операцию обновления.|  
|`SkipAllRemainingRows`|Прервать операцию обновления без вызова исключения.|  

Назначение свойству `Status` значения `ErrorsOccurred` вызовет исключение. Вызов того или иного исключения можно задать с помощью свойства `Errors`. При использовании одного из других значений `Status` исключение не вызывается.

Кроме того, для обработки ошибок для обновленных строк можно использовать свойство `ContinueUpdateOnError`. Если `DataAdapter.ContinueUpdateOnError` имеет значение `true`, когда обновление строки приводит к возникновению исключения, то текст исключения помещается в сведения `RowError` для конкретной строки, и обработка продолжается без вызова исключения. Это позволяет реагировать на ошибки, когда `Update` завершено, в отличие от события `RowUpdated`, которое позволяет реагировать на ошибки при их возникновении.

В следующем образце кода показано, как добавлять и удалять обработчики событий. Обработчик события `RowUpdating` ведет журнал всех удаленных записей с временной меткой. Обработчик события `RowUpdated` добавляет сведения об ошибке в свойство `RowError` строки в `DataSet`, подавляет исключение и продолжает обработку (зеркально отображая поведение `ContinueUpdateOnError` = `true`).

[!code-csharp[SqlDataAdapter_Events#1](~/../sqlclient/doc/samples/SqlDataAdapter_Events.cs#1)]

## <a name="fillerror-event"></a>FillError - событие

`DataAdapter` выдает событие `FillError` при возникновении ошибки во время операции `Fill`. Этот тип ошибки обычно возникает, когда данные в добавляемой строке не могут быть преобразованы в тип .NET без потери точности.

Если ошибка возникает во время операции `Fill`, то текущая строка не добавляется в `DataTable`. Событие `FillError` позволяет устранить ошибку и добавить строку, либо пропустить исключенную строку и продолжить операцию `Fill`.

Аргументы <xref:System.Data.FillErrorEventArgs>, переданные в событие `FillError` могут содержать несколько свойств, которые позволяют предпринять ответные действия и устранить ошибки. В приведенной ниже таблице показаны свойства объекта `FillErrorEventArgs`.

|Свойство|Описание|  
|--------------|-----------------|  
|`Errors`|Возникшее исключение (`Exception`).|  
|`DataTable`|Объект `DataTable` заполнялся, когда возникла ошибка.|  
|`Values`|Массив объектов со значениями строки, которая добавляется при возникновении ошибки. Нумерация элементов массива `Values` соответствует нумерации столбцов добавляемой строки. Например, `Values[0]` - значение, добавляемое как первый столбец строки.|  
|`Continue`|Позволяет указать, нужно ли вызывать исключение. Если свойство `Continue` имеет значение `false`, текущая операция `Fill` будет остановлена с вызовом исключения. Если свойство `Continue` имеет значение `true`, то операция `Fill` будет продолжена, несмотря на ошибку.|  

В следующем примере кода добавляется обработчик события для события `FillError` класса `DataAdapter`. В коде события `FillError` данный пример определяет потенциальную потерю точности, предоставляя возможность выполнить определенные действия в ответ на исключение.

[!code-csharp[SqlDataAdapter_Events#2](~/../sqlclient/doc/samples/SqlDataAdapter_Events.cs#2)]

## <a name="see-also"></a>См. также

- [Объекты DataAdapter и DataReader](dataadapters-datareaders.md)
- [События](/dotnet/standard/events/index.md)
- [Microsoft ADO.NET для SQL Server](microsoft-ado-net-sql-server.md)
